export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const PLAYER_ONE = 'X';
export type PLAYER_ONE = typeof PLAYER_ONE;

export const PLAYER_TWO = 'O';
export type PLAYER_TWO = typeof PLAYER_TWO;

export const EMPTY_FIELD = '';
export type EMPTY_FIELD = typeof EMPTY_FIELD;

export type FIELD = PLAYER_ONE | PLAYER_TWO | EMPTY_FIELD;
